name: eye4gift
favicon: null
layout_spectrum: 0.316323233069852
typography_spectrum: 0.1812406601384282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d73236'
    - '#fff116'
    - '#fefefe'
    - '#00afee'
    - '#e6999d'
  brandStrength: 0.6875
  lightness: 0.10608224663883448
  saturation: 0.6875
  rhythmicContrast: 0.24053152068518102
purpose: []
