name: eye4gift
favicon: null
layout_spectrum: 0.316323233069852
typography_spectrum: 0.1812406601384282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6790969138965011
  lightness: 0.10608224663883448
  saturation: 0.5727700616698712
  rhythmicContrast: 0.24053152068518102
purpose: []
